INSERT INTO TB_WORKER (NAME, DAILY_INCOME) 
VALUES
('Maria', 250.0);

INSERT INTO TB_WORKER (NAME, DAILY_INCOME) 
VALUES
('Alex', 300.0);

INSERT INTO TB_WORKER (NAME, DAILY_INCOME) 
VALUES
('Bob', 150.0);